name: elrond_sdk
description: Elrond SDK for Dart
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  pedantic: ^1.9.0
  convert: ^2.1.1

dev_dependencies:
  test: ^1.15.7
